name: Deploy pages

on:
  push:
     branches:
        - main
jobs:
  # a free machine-readable name for this job
  deploy:
    # specify the base operating system
    runs-on: ubuntu-latest 
    steps:
      # fetch the contents of the repository
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Prepare build environment
        # multiple Bash commands follow
        run: |
          mkdir -p build
          touch build/.nojekyll

      - name: Run pandoc
        # Always specify a version!
        uses: docker://pandoc/core:2.12
        with:
          # multi-line argument
          args: >-
            --standalone
            --output=build/index.html
            README.md

      # Use a third-party plugin to upload the content
      - name: Deploy on github pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build
